# Generated by Django 6.0.2 on 2026-03-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_listening', '0004_listeninglesson_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninglesson',
            name='video_duration_minutes',
            field=models.FloatField(default=0.0),
        ),
    ]
