# Generated by Django 6.0.2 on 2026-03-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_learning', '0003_chapter_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video_duration_minutes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
