# Generated by Django 6.0.2 on 2026-03-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_learning', '0004_chapter_video_duration_minutes_chapter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video_url',
        ),
    ]
