# Generated by Django 6.0.2 on 2026-03-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_reading', '0004_readingstory_xp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstory',
            name='background_image_url',
            field=models.URLField(max_length=500),
        ),
    ]
