# Generated by Django 6.0.2 on 2026-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_studentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
