# Generated by Django 6.0.2 on 2026-03-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0016_studentprofile_last_streak_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='points_per_activity',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='section_intermediate',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='section_professional',
        ),
    ]
