# Generated by Django 6.0.2 on 2026-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0017_remove_globalxpconfig_points_per_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalxpconfig',
            name='learning_int_threshold',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='learning_pro_threshold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='listening_int_threshold',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='listening_pro_threshold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='reading_int_threshold',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='reading_pro_threshold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='speaking_int_threshold',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='speaking_pro_threshold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='writing_int_threshold',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='globalxpconfig',
            name='writing_pro_threshold',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='listening_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='overall_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reading_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='writing_rank',
            field=models.IntegerField(default=0),
        ),
    ]
