# Generated by Django 6.0.2 on 2026-03-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0018_globalxpconfig_learning_int_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='overall_intermediate',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='overall_professional',
        ),
    ]
