# Generated by Django 6.0.2 on 2026-03-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0019_remove_globalxpconfig_overall_intermediate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='speaking_beginner_xp',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='speaking_int_threshold',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='speaking_intermediate_xp',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='speaking_pro_threshold',
        ),
        migrations.RemoveField(
            model_name='globalxpconfig',
            name='speaking_professional_xp',
        ),
    ]
